---
# file: tasks/main.yml
# Top-level installer for NVM & Node.js.
#
# @see https://github.com/creationix/nvm
#

- name: install NVM (Node Version Manager)
  git: repo=https://github.com/creationix/nvm.git dest={{ nvm_install_path }}

- name: activate NVM
  template: >
    src=../templates/activate-nvm.sh.j2
    dest="{{ ansible_user_dir }}/.zshenv.d/activate-nvm.zsh"


#
# "copy" scripts to server instead of "script" command
# to avoid "setlocale LC_CTYPE" error
#

- name: copy scripts to server
  copy: src="../files/{{ item }}"  dest="/tmp/"  mode="a+x"
  with_items:
    - install-nodejs.sh

- name: apply nvm.sh and set default version
  shell: LC_ALL="en_US.UTF-8"  /tmp/install-nodejs.sh  {{ nvm_exe_path }}  {{ nodejs_version }}

