---
- name: dotfiles | create backup directory
  file: path=~/.backups state=directory

- name: dotfiles | check for non-symlink originals
  command: test -e ~/{{ item }} -a ! -L ~/{{ item }}
  failed_when: original_check.rc > 1
  register: original_check
  with_items: '{{dotfiles}}'
  changed_when: false

- name: dotfiles | backup originals
  command:
    mv ~/{{ item.0 }} ~/.backups/
    creates=~/.backups/{{ item.0 }}
    removes=~/{{ item.0 }}
  with_together:
    - '{{dotfiles}}'
    - '{{original_check.results}}'
  when: item.1.rc == 0 # item exists and is not a symlink

- name: dotfiles | create symlinks
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  with_items: '{{dotfiles}}'

# Provide an extension point for other roles to dump .zshenv stuff into.
- name: dotfiles | make ~/.zshenv.d
  file: path=~/.zshenv.d state=directory

# Make some directories required by configuration in the dotfiles; these should
# probably be separate roles.
- name: dotfiles | create auxiliary directories
  file: path={{ item }} state=directory
  with_items:
    # mbsync will die on first sync without these.
    - ~/.mail
    - ~/.mail/Home

# Install gems
- name: dotfiles | install gems
  command: /usr/local/bin/bundler install
  args:
    chdir: roles/dotfiles/files/.mutt/scripts
    creates: roles/dotfiles/files/.mutt/scripts/vendor

