---

#####=== neovim configuration ===#####

# The specific package name used to install neovim
neovim_name: neovim

# The state in which neovim is installed
# choices: [ present, absent, latest ]
neovim_install_state: present

# vim config directory
vim_config_dir: "{{ ansible_env.HOME }}/.vim"

# The base directory relative to which all neovim config files should be stored
# Note: this is neovim's default and probably should not be changed
neovim_config_dir: "{{ xdg_config_home }}/nvim"

# Executable name for python2 pip
# default:
#   - pip
pip2_name: "{{ default_pip2_name }}"

python2_packages_to_install:
  - neovim

# Executable name for python3 pip
# default:
#   - pip3
pip3_name: "{{ default_pip3_name }}"

python3_packages_to_install:
  - neovim
  - jedi
  - mistune
  - psutil
  - setproctitle

spellfile: '{{ ansible_env.PWD }}/roles/dotfiles/files/.vim/spell/en.utf-8.add'

#####=== XDG ===#####
# http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

# The base directory relative to which user specific configuration files should be stored
# default: $XDG_CONFIG_HOME | ~/.config/
xdg_config_home: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"

# The base directory relative to which user specific data files should be stored
# default: $XDG_DATA_HOME | ~/.local/share/
xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(default_xdg_data_home) }}"

# The base directory relative to which user specific non-essential data files should be stored
# default: $XDG_CACHE_HOME | ~/.cache
xdg_cache_home: "{{ ansible_env.XDG_CACHE_HOME | default(default_xdg_cache_home) }}"

