---

# karabiner config path
karabiner_config_path: "{{ xdg_config_home }}/karabiner"

#####=== XDG ===#####
# http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

# The base directory relative to which user specific configuration files should be stored
# default: $XDG_CONFIG_HOME | ~/.config/
xdg_config_home: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"

