---
- block:
  - name: karabiner | create backup directory
    file:
      path=~/.backups
      state=directory

  - name: karabiner | check for non-symlink karabiner config
    command: test -e {{ karabiner_config_path }} -a ! -L {{ karabiner_config_path }}
    failed_when: karabiner_config_path_check.rc > 1
    register: karabiner_config_path_check
    changed_when: false

#####=== configure ===#####

- name: karabiner | backup original karabiner config
  command:
    mv {{ karabiner_config_path }} ~/.backups/
    creates=~/.backups/{{ karabiner_config_path | basename }}
    removes={{ karabiner_config_path }}
  when: karabiner_config_path_check.rc == 0 # item exists and is not a symlink

- name: karabiner | link config
  file:
    src="{{ ansible_env.PWD }}/roles/keyboard/files"
    path="{{ karabiner_config_path }}"
    state=link
    force=yes

