---
default_pip2_name: pip
default_pip3_name: pip3
default_xdg_config_home: "{{ ansible_user_dir }}/.config"
default_xdg_data_home: "{{ ansible_user_dir }}/.local/share"
default_xdg_cache_home: "{{ ansible_user_dir }}/.cache"
