---
- block:
    - name: setup
      include_vars: "{{ item }}"
      with_first_found:
        - "roles/vim/vars/{{ ansible_distribution }}.yml"
        - "roles/vim/vars/{{ ansible_os_family }}.yml"
        - roles/vim/vars/default.yml
  tags: always

#####=== install ===#####

- block:
    - name: ubuntu/debian | setup
      apt_repository: repo='ppa:neovim-ppa/unstable' state=present
      become: yes
      when: ansible_os_family == 'Debian'

    - name: package | neovim
      package: name={{ neovim_name }} state={{ neovim_install_state }}
      become: yes
      when: ansible_os_family == 'Debian'
  tags:
    - install
    - ubuntu

- block:
   - name: pip2 | neovim
     pip: name=neovim executable={{ pip2_name }} state={{ neovim_install_state }}

   - name: pip3 | neovim
     pip: name=neovim executable={{ pip3_name }} state={{ neovim_install_state }}
  ignore_errors: yes # these packages are not very essential and they are error prone
  tags:
    - install
    - neovim-python

#####=== configure ===#####

- name: install | link config folder
  file:
    src="{{ vim_config_dir }}"
    path="{{ neovim_config_dir }}"
    state=link
    force=yes

- block:
    - name: install | vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ vim_config_dir }}/autoload/plug.vim"
        force: yes

    - name: install | plugins
      command: "nvim '+silent! +PlugInstall!' +qall!"
  tags:
    - neovim-config

- name: vim | create or update spell file
  command:
    vim -u NONE -N -c 'mkspell! {{ spellfile }} | quit'
    creates={{ spellfile }}.spl
