---
- name: Check if nerd-fonts exists
  stat:
    path: ~/.config/nerd-fonts
  register: nerdFonts

- name: Install Fonts | create config folders
  file: path=~/.config state=directory

- name: Cloning nerd-fonts
  git:
    repo=https://github.com/ryanoasis/nerd-fonts
    dest=~/.config/nerd-fonts
    accept_hostkey=yes
    depth=1
  when: not nerdFonts.stat.exists
  register: fontCloned

- name: Install Fonts
  shell: ~/.config/nerd-fonts/install.sh Hasklig chdir=~/.config/nerd-fonts/
  when:
    - fontCloned|success

- name: Install Ascii Fonts
  shell: ~/.config/nerd-fonts/install.sh SourceCodePro chdir=~/.config/nerd-fonts/
  when:
    - fontCloned|success

